defaults:
  - _self_
  - model: sit_xl_2
  - dataset: imagenet_1k 
  - SI: linear

use_parametrization: false
checkpoint_path: "${hydra:runtime.cwd}/ckpts/mfm-xl2.pt"

hydra:
  run: 
    dir: ${hydra:runtime.cwd}/outputs/${now:%Y-%m-%d_%H-%M-%S}

data_dir: ${hydra:runtime.cwd}/data

save_png: false

classes: null
seed: 42

per_proc_batch_size: 128
num_samples: 50000

sampler: kernel # kernel, t0
kernel_sampler_steps: 1 # e.g. 1, 2, 4
cfg_scale: 2.5 